"""Add fields CRM tables

Revision ID: 198cbc5c5d42
Revises: aca96706ff64
Create Date: 2026-04-21 14:39:06.734985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198cbc5c5d42'
down_revision: Union[str, Sequence[str], None] = 'aca96706ff64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column(
        'probability', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('lead', sa.Column(
        'expected_close', sa.Date(), nullable=True))
    op.add_column('lead', sa.Column('deal_value', sa.Numeric(
        precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'deal_value')
    op.drop_column('lead', 'expected_close')
    op.drop_column('lead', 'probability')
    # ### end Alembic commands ###
