"""Add property_view table

Revision ID: 3ccc410406f5
Revises: 08434beeb267
Create Date: 2026-04-19 13:47:47.811212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ccc410406f5'
down_revision: Union[str, Sequence[str], None] = '08434beeb267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_view',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('view_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property_property.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_property_view_country', 'property_view', ['property_id', 'country'], unique=False)
    op.create_index('ix_property_view_dedup', 'property_view', ['property_id', 'session_id', 'view_date'], unique=True)
    op.create_index(op.f('ix_property_view_property_id'), 'property_view', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_view_property_id'), table_name='property_view')
    op.drop_index('ix_property_view_dedup', table_name='property_view')
    op.drop_index('ix_property_view_country', table_name='property_view')
    op.drop_table('property_view')
    # ### end Alembic commands ###
