"""Add property_review table

Revision ID: 5151dd9cc13d
Revises: 3ccc410406f5
Create Date: 2026-04-19 14:35:57.760362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5151dd9cc13d'
down_revision: Union[str, Sequence[str], None] = '3ccc410406f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.email'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property_property.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.email'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'user_id', name='uq_property_review_user')
    )
    op.create_index(op.f('ix_property_review_property_id'), 'property_review', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_review_user_id'), 'property_review', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_review_user_id'), table_name='property_review')
    op.drop_index(op.f('ix_property_review_property_id'), table_name='property_review')
    op.drop_table('property_review')
    # ### end Alembic commands ###
