"""Create building and property_image tables

Revision ID: 54448d4f3731
Revises: 3a1f9c2d7b8e
Create Date: 2026-04-16 17:04:27.953786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54448d4f3731'
down_revision: Union[str, Sequence[str], None] = '3a1f9c2d7b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=21, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=21, scale=6), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.email'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.email'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property_property.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('property_property', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('property_property', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.drop_column('property_property', 'main_picture_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_property', sa.Column('main_picture_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('property_property', 'is_featured')
    op.drop_column('property_property', 'image_url')
    op.drop_table('property_image')
    op.drop_table('building')
    # ### end Alembic commands ###
