"""Create user and accesstoken tables

Revision ID: 7e3dd68ec827
Revises: 
Create Date: 2026-04-16 03:05:59.698677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3dd68ec827'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('first_name', sa.Text(), nullable=False),
                    sa.Column('last_name', sa.Text(), nullable=False),
                    sa.Column('gender', sa.String(length=1), nullable=True),
                    sa.Column('phone_number', sa.Text(), nullable=True),
                    sa.Column('role', sa.Text(), nullable=False),
                    sa.Column('avatar_url', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('created_by', sa.Text(), nullable=True),
                    sa.Column('updated_by', sa.Text(), nullable=True),
                    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['created_by'], ['user.email'], ),
                    sa.ForeignKeyConstraint(['updated_by'], ['user.email'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email', name='ux_user_email')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('accesstoken',
                    sa.Column('user_id', sa.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('token', sa.String(length=43), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('token')
                    )
    op.create_index(op.f('ix_accesstoken_created_at'),
                    'accesstoken', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accesstoken_created_at'), table_name='accesstoken')
    op.drop_table('accesstoken')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
