"""Country make name nullable

Revision ID: f3b2572b2a68
Revises: 594e2499de92
Create Date: 2026-04-16 13:12:00.865209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b2572b2a68'
down_revision: Union[str, Sequence[str], None] = '594e2499de92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('country_name_key'), 'country', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('country_name_key'), 'country', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('country', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
