homepage_listings = [
    {"title": "Penthouse Panoramique - Plateau", "link": "#", "bg_image": "https://picsum.photos/id/10/1024/768", "is_featured": True, "type": "rent", "price": "2.500.000", "currency": "F CFA", "location": "Dakar Plateau", "property_type": "Appartement", "bedroom_nbr": 4, "bthroom_nbr": 4, "land_size": 350},
    {"title": "Villa Oasis - Somone", "link": "#", "bg_image": "https://picsum.photos/id/11/1024/768", "is_featured": True, "type": "sale", "price": "350.000.000", "currency": "F CFA", "location": "La Somone", "property_type": "Villa", "bedroom_nbr": 6, "bthroom_nbr": 5, "land_size": 1000},
    {"title": "Studio Loft - Ngor", "link": "#", "bg_image": "https://picsum.photos/id/164/1024/768", "is_featured": False, "type": "furnished", "price": "75.000", "currency": "F CFA / nuit", "location": "Ngor", "property_type": "Studio", "bedroom_nbr": 1, "bthroom_nbr": 1, "land_size": 60},
    {"title": "Terrain Vue Mer - Toubab Dialaw", "link": "#", "bg_image": "https://picsum.photos/id/210/1024/768", "is_featured": False, "type": "sale", "price": "45.000.000", "currency": "F CFA", "location": "Toubab Dialaw", "property_type": "Terrain", "bedroom_nbr": None, "bthroom_nbr": None, "land_size": 500},
    {"title": "Appartement Familial - Hann Maristes", "link": "#", "bg_image": "https://picsum.photos/id/162/1024/768", "is_featured": False, "type": "rent", "price": "600.000", "currency": "F CFA", "location": "Hann Maristes", "property_type": "Appartement", "bedroom_nbr": 3, "bthroom_nbr": 2, "land_size": 140},
    {"title": "Duplex Moderne - Point E", "link": "#", "bg_image": "https://picsum.photos/id/24/1024/768", "is_featured": True, "type": "sale", "price": "220.000.000", "currency": "F CFA", "location": "Point E, Dakar", "property_type": "Duplex", "bedroom_nbr": 4, "bthroom_nbr": 4, "land_size": 280},
    {"title": "Villa de Vacances - Saly", "link": "#", "bg_image": "https://picsum.photos/id/182/1024/768", "is_featured": False, "type": "furnished", "price": "150.000", "currency": "F CFA / nuit", "location": "Saly Joseph", "property_type": "Villa", "bedroom_nbr": 4, "bthroom_nbr": 3, "land_size": 450},
    {"title": "Bureau Open Space - VDN", "link": "#", "bg_image": "https://picsum.photos/id/201/1024/768", "is_featured": False, "type": "rent", "price": "1.800.000", "currency": "F CFA", "location": "VDN, Dakar", "property_type": "Bureau", "bedroom_nbr": None, "bthroom_nbr": 2, "land_size": 200},
    {"title": "Maison de Ville - Ouakam", "link": "#", "bg_image": "https://picsum.photos/id/122/1024/768", "is_featured": True, "type": "sale", "price": "125.000.000", "currency": "F CFA", "location": "Ouakam", "property_type": "Maison", "bedroom_nbr": 4, "bthroom_nbr": 2, "land_size": 150},
    {"title": "Appartement Chic - Fann", "link": "#", "bg_image": "https://picsum.photos/id/42/1024/768", "is_featured": False, "type": "furnished", "price": "1.200.000", "currency": "F CFA / mois", "location": "Fann Résidence", "property_type": "Appartement", "bedroom_nbr": 2, "bthroom_nbr": 2, "land_size": 110},
    {"title": "Terrain Zone Franche - Mbao", "link": "#", "bg_image": "https://picsum.photos/id/214/1024/768", "is_featured": False, "type": "sale", "price": "35.000.000", "currency": "F CFA", "location": "Mbao", "property_type": "Terrain", "bedroom_nbr": None, "bthroom_nbr": None, "land_size": 400},
    {"title": "Villa Prestige - Sacré Cœur", "link": "#", "bg_image": "https://picsum.photos/id/111/1024/768", "is_featured": True, "type": "sale", "price": "280.000.000", "currency": "F CFA", "location": "Sacré Cœur 3", "property_type": "Villa", "bedroom_nbr": 5, "bthroom_nbr": 5, "land_size": 320},
    {"title": "Loft Industriel - Bel Air", "link": "#", "bg_image": "https://picsum.photos/id/160/1024/768", "is_featured": False, "type": "rent", "price": "900.000", "currency": "F CFA", "location": "Bel Air", "property_type": "Loft", "bedroom_nbr": 2, "bthroom_nbr": 1, "land_size": 130},
    {"title": "Maison de Charme - Gorée", "link": "#", "bg_image": "https://picsum.photos/id/163/1024/768", "is_featured": True, "type": "sale", "price": "400.000.000", "currency": "F CFA", "location": "Île de Gorée", "property_type": "Maison Historique", "bedroom_nbr": 5, "bthroom_nbr": 3, "land_size": 250},
    {"title": "Studio Étudiant - Liberté 5", "link": "#", "bg_image": "https://picsum.photos/id/180/1024/768", "is_featured": False, "type": "rent", "price": "180.000", "currency": "F CFA", "location": "Liberté 5", "property_type": "Studio", "bedroom_nbr": 1, "bthroom_nbr": 1, "land_size": 35}
]

search_listings = [
    {
        "id": 1,
        "title": "Villa d'Exception aux Almadies",
        "property_type": "Villa",
        "price": "3 500 000 FCFA",
        "location": "Almadies, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/villa1/800/600",
        "is_featured": True,
        "has_period": True,
        "period": "/mois",
        "land_size": "800m²",
        "bedroom_nbr": 6,
        "bthroom_nbr": 5,
        "link": "/listing/1",
        "full_description": "Une demeure prestigieuse offrant des volumes généreux et des finitions haut de gamme au cœur du quartier le plus prisé de Dakar.",
        "amenities": ["Piscine", "Groupe Électrogène", "Gardiennage 24/7"],
        "agent": {"name": "Pape Ba", "whatsapp": "+221770000000"}
    },
    {
        "id": 2,
        "title": "Appartement Moderne Plateau",
        "property_type": "Appartement F4",
        "price": "1 200 000 FCFA",
        "location": "Plateau, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/apt2/800/600",
        "is_featured": False,
        "has_period": True,
        "period": "/mois",
        "land_size": "150m²",
        "bedroom_nbr": 3,
        "bthroom_nbr": 2,
        "link": "/listing/2",
        "full_description": "Situé en plein centre-ville, cet appartement offre une vue imprenable sur le port et un accès immédiat aux commodités.",
        "amenities": ["Ascenseur", "Parking Sous-sol", "Climatisation"],
        "agent": {"name": "Dswade", "whatsapp": "+221770000001"}
    },
    {
        "id": 3,
        "title": "Terrain avec Titre Foncier",
        "property_type": "Terrain",
        "price": "45 000 000 FCFA",
        "location": "Diamniadio, Dakar",
        "type": "sale",
        "bg_image": "https://picsum.photos/seed/land3/800/600",
        "is_featured": True,
        "has_period": False,
        "land_size": "200m²",
        "bedroom_nbr": 0,
        "bthroom_nbr": 0,
        "link": "/listing/3",
        "full_description": "Terrain constructible idéalement situé dans le pôle urbain de Diamniadio, parfait pour un projet résidentiel.",
        "amenities": ["Viabilisé", "Accès Goudronné"],
        "agent": {"name": "Pape Ba", "whatsapp": "+221770000000"}
    },
    {
        "id": 4,
        "title": "Parking Sécurisé Centre-Ville",
        "property_type": "Parking",
        "price": "75 000 FCFA",
        "location": "Plateau, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/park4/800/600",
        "is_featured": False,
        "has_period": True,
        "period": "/mois",
        "land_size": "15m²",
        "bedroom_nbr": 0,
        "bthroom_nbr": 0,
        "link": "/listing/4",
        "full_description": "Emplacement de parking sécurisé avec accès badge 24h/24 dans un immeuble moderne du Plateau.",
        "amenities": ["Vidéosurveillance", "Accès Badge"],
        "agent": {"name": "Dswade", "whatsapp": "+221770000001"}
    },
    {
        "id": 5,
        "title": "Studio Cosy Ngor Virage",
        "property_type": "Appartement F2",
        "price": "50 000 FCFA",
        "location": "Ngor, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/studio5/800/600",
        "is_featured": False,
        "has_period": True,
        "period": "/jour",
        "land_size": "50m²",
        "bedroom_nbr": 1,
        "bthroom_nbr": 1,
        "link": "/listing/5",
        "full_description": "Studio meublé avec goût, idéal pour les séjours de courte durée, à deux pas de la plage du Virage.",
        "amenities": ["Wifi", "Smart TV", "Ménage Inclus"],
        "agent": {"name": "Pape Ba", "whatsapp": "+221770000000"}
    },
    {
        "id": 6,
        "title": "Immeuble R+5 Neuf",
        "property_type": "Immeuble",
        "price": "850 000 000 FCFA",
        "location": "Mermoz, Dakar",
        "type": "sale",
        "bg_image": "https://picsum.photos/seed/build6/800/600",
        "is_featured": True,
        "has_period": False,
        "land_size": "400m²",
        "bedroom_nbr": 15,
        "bthroom_nbr": 10,
        "link": "/listing/6",
        "full_description": "Immeuble de rapport composé de plusieurs appartements, idéal pour un investissement locatif rentable.",
        "amenities": ["Réserve d'eau", "Terrasse Commune"],
        "agent": {"name": "Dswade", "whatsapp": "+221770000001"}
    },
    {
        "id": 7,
        "title": "Bureau Standing Point E",
        "property_type": "Bureau",
        "price": "1 800 000 FCFA",
        "location": "Point E, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/office7/800/600",
        "is_featured": True,
        "has_period": True,
        "period": "/mois",
        "land_size": "220m²",
        "rooms_total": 5,
        "bthroom_nbr": 2,
        "link": "/listing/7",
        "full_description": "Espace de travail professionnel haut standing, climatisé et câblé, situé dans le quartier d'affaires du Point E.",
        "amenities": ["Fibre Optique", "Salle de Réunion", "Kitchenette"],
        "agent": {"name": "Pape Ba", "whatsapp": "+221770000000"}
    },
    {
        "id": 8,
        "title": "Appartement Familial Sacré-Cœur",
        "property_type": "Appartement F5",
        "price": "650 000 FCFA",
        "location": "Sacré-Cœur 3, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/house8/800/600",
        "is_featured": False,
        "has_period": True,
        "period": "/mois",
        "land_size": "180m²",
        "bedroom_nbr": 4,
        "bthroom_nbr": 3,
        "link": "/listing/8",
        "full_description": "Grand appartement F5 spacieux et lumineux, parfait pour une famille, situé dans un quartier calme et sécurisé.",
        "amenities": ["Balcon", "Réservoir d'eau", "Parking Extérieur"],
        "agent": {"name": "Dswade", "whatsapp": "+221770000001"}
    },
    {
        "id": 9,
        "title": "Penthouse F5 de Luxe",
        "property_type": "Appartement F5",
        "price": "2 800 000 FCFA",
        "location": "Fann Résidence, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/pent9/800/600",
        "is_featured": True,
        "has_period": True,
        "period": "/mois",
        "land_size": "300m²",
        "bedroom_nbr": 4,
        "bthroom_nbr": 4,
        "link": "/listing/9",
        "full_description": "Penthouse exclusif avec terrasse panoramique offrant une vue exceptionnelle sur l'Océan Atlantique.",
        "amenities": ["Jacuzzi", "Cuisine Équipée", "Domotique"],
        "agent": {"name": "Pape Ba", "whatsapp": "+221770000000"}
    },
    {
        "id": 10,
        "title": "Appartement F3 Moderne",
        "property_type": "Appartement F3",
        "price": "350 000 FCFA",
        "location": "Liberté 6, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/apt10/800/600",
        "is_featured": False,
        "has_period": True,
        "period": "/mois",
        "land_size": "95m²",
        "bedroom_nbr": 2,
        "bthroom_nbr": 2,
        "link": "/listing/10",
        "full_description": "Appartement F3 récent avec de belles finitions, situé à proximité des commerces et du transport.",
        "amenities": ["Interphone", "Sécurité nocturne"],
        "agent": {"name": "Dswade", "whatsapp": "+221770000001"}
    },
    # --- EXTREME LUXURY ---
    {
        "id": 11,
        "title": "Sky-High Penthouse - Tour de l'Indépendance",
        "property_type": "Appartement de Luxe",
        "price": "5 500 000 FCFA",
        "location": "Plateau, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/lux1/800/600",
        "is_featured": True, "has_period": True, "period": "/mois",
        "land_size": "450m²", "bedroom_nbr": 5, "bthroom_nbr": 6, "link": "/listing/11",
        "full_description": "Le plus haut penthouse résidentiel de Dakar avec une vue à 360° sur l'île de Gorée et le Monument de la Renaissance.",
        "amenities": ["Piscine Privée", "Héliport", "Domotique Totale", "Salle de Cinéma", "Cave à Vin"],
        "agent": {"name": "Awa Diop", "whatsapp": "+221771234567"}
    },
    {
        "id": 12,
        "title": "Palais de Marbre - Corniche Ouest",
        "property_type": "Villa Royale",
        "price": "12 000 000 FCFA",
        "location": "Fann, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/lux2/800/600",
        "is_featured": True, "has_period": True, "period": "/mois",
        "land_size": "1500m²", "bedroom_nbr": 8, "bthroom_nbr": 9, "link": "/listing/12",
        "full_description": "Une merveille architecturale sur la falaise, entièrement vêtue de marbre d'Italie et de bois précieux.",
        "amenities": ["Ascenseur Vitré", "Salle de Sport", "Spa", "Quai Privé", "Double Garage"],
        "agent": {"name": "Malick Sy", "whatsapp": "+221709876543"}
    },
    # --- EXTREME COMMERCIAL ---
    {
        "id": 13,
        "title": "Rooftop Lounge & Bar - Horizon Plateau",
        "property_type": "Local Commercial",
        "price": "3 800 000 FCFA",
        "location": "Plateau, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/comm1/800/600",
        "is_featured": True, "has_period": True, "period": "/mois",
        "land_size": "300m²", "rooms_total": 3, "bthroom_nbr": 4, "link": "/listing/13",
        "full_description": "Espace commercial unique au 12ème étage, idéal pour un restaurant ou club privé avec vue panoramique.",
        "amenities": ["Terrasse Panoramique", "Cuisine Industrielle", "Monte-charge", "Sono Intégrée"],
        "agent": {"name": "Doudou Ndiaye", "whatsapp": "+221765554433"}
    },
    {
        "id": 14,
        "title": "Showroom Automobile - Route de Rufisque",
        "property_type": "Local Commercial",
        "price": "150 000 000 FCFA",
        "location": "Pikine, Dakar",
        "type": "sale",
        "bg_image": "https://picsum.photos/seed/comm2/800/600",
        "is_featured": False, "has_period": False,
        "land_size": "2000m²", "rooms_total": 8, "bthroom_nbr": 2, "link": "/listing/14",
        "full_description": "Immense surface vitrée sur l'axe principal, parfaite pour concessionnaire ou centre logistique.",
        "amenities": ["Parking Clients (50 places)", "Atelier Mécanique", "Bureaux Mezzanine"],
        "agent": {"name": "Fatou Gomis", "whatsapp": "+221781112233"}
    },
    # --- EXTREME BUDGET / STUDENT ---
    {
        "id": 15,
        "title": "Chambre Étudiante UCAD - Liberté 1",
        "property_type": "Studio Étudiant",
        "price": "45 000 FCFA",
        "location": "Liberté 1, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/stud1/800/600",
        "is_featured": False, "has_period": True, "period": "/mois",
        "land_size": "12m²", "bedroom_nbr": 1, "bthroom_nbr": 1, "link": "/listing/15",
        "full_description": "Petite chambre fonctionnelle proche des universités, électricité et eau partagées.",
        "amenities": ["Ventilateur", "Proximité Bus", "Zone Calme"],
        "agent": {"name": "Ousmane Kane", "whatsapp": "+221773339988"}
    },
    {
        "id": 16,
        "title": "Box de Stockage Sécurisé - Zone B",
        "property_type": "Entrepôt",
        "price": "5 000 FCFA",
        "location": "Zone B, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/box1/800/600",
        "is_featured": False, "has_period": True, "period": "/jour",
        "land_size": "5m²", "bedroom_nbr": 0, "bthroom_nbr": 0, "link": "/listing/16",
        "full_description": "Location de micro-box pour archivage ou petit stock commerçant.",
        "amenities": ["Cadenas Fourni", "Vidéosurveillance", "Accès 24/7"],
        "agent": {"name": "Bineta Diallo", "whatsapp": "+221704445566"}
    },
    # --- UNIQUE / EXOTIC ---
    {
        "id": 17,
        "title": "Villa Écologique Solaire - Lac Rose",
        "property_type": "Villa",
        "price": "85 000 000 FCFA",
        "location": "Lac Rose, Dakar",
        "type": "sale",
        "bg_image": "https://picsum.photos/seed/eco1/800/600",
        "is_featured": True, "has_period": False,
        "land_size": "600m²", "bedroom_nbr": 3, "bthroom_nbr": 2, "link": "/listing/17",
        "full_description": "Maison 100% autonome en énergie solaire avec système de récupération d'eau de pluie.",
        "amenities": ["Panneaux Solaires", "Potager Bio", "Puits Privé", "Briques de Terre Compressée"],
        "agent": {"name": "Cheikh Fall", "whatsapp": "+221772223344"}
    },
    {
        "id": 18,
        "title": "Hôtel Particulier - Gorée",
        "property_type": "Bâtiment Historique",
        "price": "450 000 000 FCFA",
        "location": "Île de Gorée",
        "type": "sale",
        "bg_image": "https://picsum.photos/seed/hist1/800/600",
        "is_featured": True, "has_period": False,
        "land_size": "250m²", "bedroom_nbr": 5, "bthroom_nbr": 3, "link": "/listing/18",
        "full_description": "Authentique maison coloniale rénovée avec vue sur mer, au calme absolu de l'île sans voitures.",
        "amenities": ["Patio Intérieur", "Vue Mer Directe", "Rénovation de Luxe"],
        "agent": {"name": "Idrissa Seck", "whatsapp": "+221769998877"}
    },
    {
        "id": 19,
        "title": "Studio Loft Industriel - Hann Maristes",
        "property_type": "Appartement F2",
        "price": "450 000 FCFA",
        "location": "Hann Maristes, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/loft1/800/600",
        "is_featured": False, "has_period": True, "period": "/mois",
        "land_size": "85m²", "bedroom_nbr": 1, "bthroom_nbr": 1, "link": "/listing/19",
        "full_description": "Concept ouvert avec briques apparentes et grandes fenêtres, style new-yorkais.",
        "amenities": ["Cuisine Américaine", "Parking Sécurisé", "Climatisation Centrale"],
        "agent": {"name": "Mariama Ba", "whatsapp": "+221785556677"}
    },
    {
        "id": 20,
        "title": "Bureau de Coworking - Ngor",
        "property_type": "Bureau",
        "price": "15 000 FCFA",
        "location": "Ngor, Dakar",
        "type": "rent",
        "bg_image": "https://picsum.photos/seed/cowork1/800/600",
        "is_featured": False, "has_period": True, "period": "/jour",
        "land_size": "10m²", "rooms_total": 1, "bthroom_nbr": 1, "link": "/listing/20",
        "full_description": "Bureau partagé avec ambiance startup, café à volonté et internet fibre.",
        "amenities": ["Cafetière", "Tableau Blanc", "Zone Chill"],
        "agent": {"name": "Lamine Gning", "whatsapp": "+221703332211"}
    },
    # ... (I will continue with 10 more to reach the 20 requested)
    {
        "id": 21, "title": "Duplex Familial Ouakam", "property_type": "Appartement F6", "price": "950 000 FCFA", 
        "location": "Ouakam, Dakar", "type": "rent", "bg_image": "https://picsum.photos/seed/dup1/800/600",
        "is_featured": False, "has_period": True, "period": "/mois", "land_size": "220m²", "bedroom_nbr": 5, "bthroom_nbr": 4,
        "link": "/listing/21", "full_description": "Grand duplex près de la statue de la Renaissance.",
        "amenities": ["Balcons multiples", "Chambre Domestique"], "agent": {"name": "Sophie Ndiaye", "whatsapp": "+221774443322"}
    },
    {
        "id": 22, "title": "Villa d'Hôtes - Somone", "property_type": "Villa", "price": "150 000 FCFA", 
        "location": "Somone", "type": "rent", "bg_image": "https://picsum.photos/seed/som1/800/600",
        "is_featured": True, "has_period": True, "period": "/jour", "land_size": "500m²", "bedroom_nbr": 4, "bthroom_nbr": 4,
        "link": "/listing/22", "full_description": "Magnifique villa avec piscine pour vos weekends.",
        "amenities": ["Piscine", "Barbecue", "Plage à 200m"], "agent": {"name": "Abdoulaye Wade", "whatsapp": "+221761110000"}
    },
    {
        "id": 23, "title": "Boutique d'Angle - Sacré Cœur", "property_type": "Local Commercial", "price": "2 500 000 FCFA", 
        "location": "Sacré Cœur 2, Dakar", "type": "rent", "bg_image": "https://picsum.photos/seed/shop1/800/600",
        "is_featured": False, "has_period": True, "period": "/mois", "land_size": "120m²", "rooms_total": 2, "bthroom_nbr": 1,
        "link": "/listing/23", "full_description": "Emplacement stratégique avec visibilité maximale.",
        "amenities": ["Vitrine Blindée", "Climatisation"], "agent": {"name": "Aminata Touré", "whatsapp": "+221782228811"}
    },
    {
        "id": 24, "title": "Appartement Meublé Chic - Almadies", "property_type": "Appartement F3", "price": "85 000 FCFA", 
        "location": "Almadies, Dakar", "type": "rent", "bg_image": "https://picsum.photos/seed/furnished1/800/600",
        "is_featured": True, "has_period": True, "period": "/jour", "land_size": "110m²", "bedroom_nbr": 2, "bthroom_nbr": 2,
        "link": "/listing/24", "full_description": "Décoration contemporaine, idéal pour business travel.",
        "amenities": ["Netflix", "Ménage quotidien", "Netflix"], "agent": {"name": "Papa Diouf", "whatsapp": "+221775551122"}
    },
    {
        "id": 25, "title": "Terrain Agricole - Kayar", "property_type": "Terrain Agricole", "price": "15 000 000 FCFA", 
        "location": "Kayar", "type": "sale", "bg_image": "https://picsum.photos/seed/farm1/800/600",
        "is_featured": False, "has_period": False, "land_size": "10000m²", "bedroom_nbr": 0, "bthroom_nbr": 0,
        "link": "/listing/25", "full_description": "Terre fertile pour maraîchage avec forage installé.",
        "amenities": ["Forage", "Clôture Grillage"], "agent": {"name": "Moussa Sarr", "whatsapp": "+221706663344"}
    },
    {
        "id": 26, "title": "Villa Bassin - Saly Portudal", "property_type": "Villa", "price": "225 000 000 FCFA", 
        "location": "Saly", "type": "sale", "bg_image": "https://picsum.photos/seed/saly1/800/600",
        "is_featured": False, "has_period": False, "land_size": "800m²", "bedroom_nbr": 4, "bthroom_nbr": 4,
        "link": "/listing/26", "full_description": "Villa balnéaire dans résidence calme.",
        "amenities": ["Plage Privée", "Piscine", "Golf"], "agent": {"name": "Yacine Fall", "whatsapp": "+221774441111"}
    },
    {
        "id": 27, "title": "Bureau Open Space - VDN", "property_type": "Bureau", "price": "3 200 000 FCFA", 
        "location": "VDN, Dakar", "type": "rent", "bg_image": "https://picsum.photos/seed/vdn1/800/600",
        "is_featured": True, "has_period": True, "period": "/mois", "land_size": "350m²", "rooms_total": 1, "bthroom_nbr": 3,
        "link": "/listing/27", "full_description": "Plateau de bureaux modulables sur la VDN.",
        "amenities": ["Fibre Optique", "Ascenseur", "Parking"], "agent": {"name": "Karim Wade", "whatsapp": "+221768884455"}
    },
    {
        "id": 28, "title": "Studette Cosy - Médina", "property_type": "Appartement F1", "price": "125 000 FCFA", 
        "location": "Médina, Dakar", "type": "rent", "bg_image": "https://picsum.photos/seed/med1/800/600",
        "is_featured": False, "has_period": True, "period": "/mois", "land_size": "25m²", "bedroom_nbr": 1, "bthroom_nbr": 1,
        "link": "/listing/28", "full_description": "Logement typique au cœur de la Médina.",
        "amenities": ["Toit terrasse", "Proximité Marché"], "agent": {"name": "Bamba Diop", "whatsapp": "+221772225588"}
    },
    {
        "id": 29, "title": "Villa Moderne - Keur Massar", "property_type": "Villa", "price": "55 000 000 FCFA", 
        "location": "Keur Massar", "type": "sale", "bg_image": "https://picsum.photos/seed/km1/800/600",
        "is_featured": False, "has_period": False, "land_size": "150m²", "bedroom_nbr": 3, "bthroom_nbr": 2,
        "link": "/listing/29", "full_description": "Villa neuve R+1 dans zone en plein essor.",
        "amenities": ["Garage", "Finition Italienne"], "agent": {"name": "Khady Ndiaye", "whatsapp": "+221785552211"}
    },
    {
        "id": 30, "title": "Entrepôt Logistique - Rufisque", "property_type": "Entrepôt", "price": "8 000 000 FCFA", 
        "location": "Rufisque", "type": "rent", "bg_image": "https://picsum.photos/seed/ruf1/800/600",
        "is_featured": True, "has_period": True, "period": "/mois", "land_size": "5000m²", "rooms_total": 4, "bthroom_nbr": 2,
        "link": "/listing/30", "full_description": "Grande capacité pour stockage industriel.",
        "amenities": ["Accès Camions", "Sécurité incendie"], "agent": {"name": "Ibrahima Fall", "whatsapp": "+221762220099"}
    }
]