homepage_listings = [
    {"title": "Penthouse Panoramique - Plateau", "link": "#", "bg_image": "https://picsum.photos/id/10/1024/768", "is_featured": True, "type": "rent", "price": "2.500.000", "currency": "F CFA", "location": "Dakar Plateau", "property_type": "Appartement", "bedroom_nbr": 4, "bthroom_nbr": 4, "land_size": 350},
    {"title": "Villa Oasis - Somone", "link": "#", "bg_image": "https://picsum.photos/id/11/1024/768", "is_featured": True, "type": "sale", "price": "350.000.000", "currency": "F CFA", "location": "La Somone", "property_type": "Villa", "bedroom_nbr": 6, "bthroom_nbr": 5, "land_size": 1000},
    {"title": "Studio Loft - Ngor", "link": "#", "bg_image": "https://picsum.photos/id/164/1024/768", "is_featured": False, "type": "furnished", "price": "75.000", "currency": "F CFA / nuit", "location": "Ngor", "property_type": "Studio", "bedroom_nbr": 1, "bthroom_nbr": 1, "land_size": 60},
    {"title": "Terrain Vue Mer - Toubab Dialaw", "link": "#", "bg_image": "https://picsum.photos/id/210/1024/768", "is_featured": False, "type": "sale", "price": "45.000.000", "currency": "F CFA", "location": "Toubab Dialaw", "property_type": "Terrain", "bedroom_nbr": None, "bthroom_nbr": None, "land_size": 500},
    {"title": "Appartement Familial - Hann Maristes", "link": "#", "bg_image": "https://picsum.photos/id/162/1024/768", "is_featured": False, "type": "rent", "price": "600.000", "currency": "F CFA", "location": "Hann Maristes", "property_type": "Appartement", "bedroom_nbr": 3, "bthroom_nbr": 2, "land_size": 140},
    {"title": "Duplex Moderne - Point E", "link": "#", "bg_image": "https://picsum.photos/id/24/1024/768", "is_featured": True, "type": "sale", "price": "220.000.000", "currency": "F CFA", "location": "Point E, Dakar", "property_type": "Duplex", "bedroom_nbr": 4, "bthroom_nbr": 4, "land_size": 280},
    {"title": "Villa de Vacances - Saly", "link": "#", "bg_image": "https://picsum.photos/id/182/1024/768", "is_featured": False, "type": "furnished", "price": "150.000", "currency": "F CFA / nuit", "location": "Saly Joseph", "property_type": "Villa", "bedroom_nbr": 4, "bthroom_nbr": 3, "land_size": 450},
    {"title": "Bureau Open Space - VDN", "link": "#", "bg_image": "https://picsum.photos/id/201/1024/768", "is_featured": False, "type": "rent", "price": "1.800.000", "currency": "F CFA", "location": "VDN, Dakar", "property_type": "Bureau", "bedroom_nbr": None, "bthroom_nbr": 2, "land_size": 200},
    {"title": "Maison de Ville - Ouakam", "link": "#", "bg_image": "https://picsum.photos/id/122/1024/768", "is_featured": True, "type": "sale", "price": "125.000.000", "currency": "F CFA", "location": "Ouakam", "property_type": "Maison", "bedroom_nbr": 4, "bthroom_nbr": 2, "land_size": 150},
    {"title": "Appartement Chic - Fann", "link": "#", "bg_image": "https://picsum.photos/id/42/1024/768", "is_featured": False, "type": "furnished", "price": "1.200.000", "currency": "F CFA / mois", "location": "Fann Résidence", "property_type": "Appartement", "bedroom_nbr": 2, "bthroom_nbr": 2, "land_size": 110},
    {"title": "Terrain Zone Franche - Mbao", "link": "#", "bg_image": "https://picsum.photos/id/214/1024/768", "is_featured": False, "type": "sale", "price": "35.000.000", "currency": "F CFA", "location": "Mbao", "property_type": "Terrain", "bedroom_nbr": None, "bthroom_nbr": None, "land_size": 400},
    {"title": "Villa Prestige - Sacré Cœur", "link": "#", "bg_image": "https://picsum.photos/id/111/1024/768", "is_featured": True, "type": "sale", "price": "280.000.000", "currency": "F CFA", "location": "Sacré Cœur 3", "property_type": "Villa", "bedroom_nbr": 5, "bthroom_nbr": 5, "land_size": 320},
    {"title": "Loft Industriel - Bel Air", "link": "#", "bg_image": "https://picsum.photos/id/160/1024/768", "is_featured": False, "type": "rent", "price": "900.000", "currency": "F CFA", "location": "Bel Air", "property_type": "Loft", "bedroom_nbr": 2, "bthroom_nbr": 1, "land_size": 130},
    {"title": "Maison de Charme - Gorée", "link": "#", "bg_image": "https://picsum.photos/id/163/1024/768", "is_featured": True, "type": "sale", "price": "400.000.000", "currency": "F CFA", "location": "Île de Gorée", "property_type": "Maison Historique", "bedroom_nbr": 5, "bthroom_nbr": 3, "land_size": 250},
    {"title": "Studio Étudiant - Liberté 5", "link": "#", "bg_image": "https://picsum.photos/id/180/1024/768", "is_featured": False, "type": "rent", "price": "180.000", "currency": "F CFA", "location": "Liberté 5", "property_type": "Studio", "bedroom_nbr": 1, "bthroom_nbr": 1, "land_size": 35}
]